[features]
seeds = false
skip-lint = false
[programs.devnet]
election_contract = "5LccFhaydDuGqX24evbxuNu9yp1BZZNEtBbgTJCQ1zBv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/socialb/Desktop/Workspace/socialB/Blockchain/SeCbhUgwfifKUVc3Ut5Z7hRCRMsPyFr1Z4hyargXYYv.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
